### ISSUE TITLE
As a user, I want to see all the cards with the same color

### ISSUE THREAD

**Issue by bes-alielzein** [BesLogic/releaf-canopeum#212]
Inconsistent background color (/Sites) 
The background color of all the cards should be consistent, the right color code is:  #FFFAF5 (`$cream`)

![Image](https://github.com/user-attachments/assets/f31519a3-4fc8-4991-a837-bc921ae43f9f)

**Comment by Samuel-Therrien-Beslogic** [comment]
There's still some cards still using the white background.
`card-bg-color` should be a variable, and we should preferably target CSS-classes of existing "card" and card-like components so that they're applied in a "themed" manner (see https://github.com/BesLogic/releaf-canopeum/issues/249 ) and reduce the need to manually set it to individual custom components.
